### PR TITLE
Adds info on how to install `fit`

### PR DESCRIPTION
**Pull request by mathewmorris**
Hey! looking forward to working on this project more. I think this is the bare minimum of how to get the installation up globally. 
I didn't bump the version since I'm not sure how you want to handle that part of the project. If you want, I can create another PR to start adding more documentation for things such as: contributing, versioning, testing, development, etc.
I'm a huge fan of the wiki feature that Github offers since it creates an entirely new repo and doesn't muck up your project git history.

Anyway, here's my first attempt at a contribution! Thanks!

### CODE REVIEW

**Comment by mathewmorris** [comment]
This also refers to #2

**Review by mtliendo — CHANGES_REQUESTED** [review]
I think instead of having the script to link, the user can just use the `npm link` command to create a symbolic link until the package is published to npm.

**Review by mtliendo — APPROVED** [review]

**Comment by mtliendo** [comment]
@jchiatt any objections?

**Comment by jchiatt** [comment]
@mathewmorris @mtliendo sorry I missed this! what's the advantage of `npm link` over `npm install -g` ?

**Comment by mtliendo** [comment]
Just to follow up, link will create a symlink and not pollute the global space. Which tends to be a better approach when the package isn't ready to be published.

**Comment by jchiatt** [comment]
> not pollute the global space

@mtliendo as in, adding a global executable that doesn't really do anything? I assume we'd want it to be global once it's ready right?

**Comment by mtliendo** [comment]
Yea.  Once the package is published, the instructions would have to be changed/ammended. This PR is more of an "in the meantime".

**Comment by mathewmorris** [comment]
@mtliendo @jchiatt You guys got it 👍 We can update later!

**Pull request merged**
